### PR TITLE
Add missing custom fields to categories

### PR DESCRIPTION
**Pull request by andersekdahl**
Not sure if this is the only thing required, but it looked like it. Solves https://github.com/commercetools/commercetools-dotnet-sdk/issues/116 if that's the case.

### CODE REVIEW

**Comment by jenschude** [comment]
Could you add the custom field also directly to the CategoryDraft please? But yeah this should be sufficient

**Comment by jenschude** [comment]
Ah one thing may be missing is the respective update actions else you can't update the custom field

**Comment by jenschude** [comment]
Like here:

https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Customers/UpdateActions/SetCustomFieldAction.cs

https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Customers/UpdateActions/SetCustomTypeAction.cs

**Comment by andersekdahl** [comment]
That already seems to exist:
https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Categories/CategoryDraft.cs#L79

https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Categories/UpdateActions/SetCustomTypeAction.cs

**Comment by jenschude** [comment]
Ah perfect 👍

**Pull request merged**
