### PR TITLE
Added ShippingRate Tiers

### PR DESCRIPTION
**Pull request by btastic**
Fixes https://github.com/commercetools/commercetools-dotnet-sdk/issues/76

### CODE REVIEW

**Comment by jenschude** [comment]
The implementation is not supporting all type of shipping rate tiers. The tiers are a polymorphic object. Could you please add the missing CartScore and and CartClassification tiers too?

**Comment by btastic** [comment]
Oh sorry I missed that one! Will have a look at it once I'm home.

**Comment by jenschude** [comment]
In the mean time I merged and released your other changes 👍

**Comment by btastic** [comment]
That was quite cool. So what I did is:

- Make `Tier` an abstract class with default properties like `Type` and `Price`
- Have three different Tier classes: `CartClassificationTier`, `CartValueTier` and `CartScoreTier` inheriting from `Tier`.
- Each of them have their own properties and constructors.

Now the challenge was: Does it work when serializing? And it didn't at first. But I quickly found that you can use a custom `JsonConverter` and so the `TierJsonConverter` was born.

- `CanConvert` will make sure that only `Tier` objects are allowed to be converted using this converter.
- `ReadJson` will check the `type` property of the json, and evaluate in a switch statement, which type it really should convert to.
- Throwing an exception when there is an unknown `Tier` type for good measure.

Finally using the `TierJsonConverter` whereever needed (`Json.Deserialize...` was only used in `Client` and I added the property to each call, to use the new `JsonSerializerSettings`.

**Comment by btastic** [comment]
I just saw that it seems that I changed the whole `Client.cs`. But it just changed the whole file  due to inconsistent line endings I think. I can change and fix that If necessary.

**Comment by btastic** [comment]
Made some changes to conform with existing JsonConverters

**Pull request merged**
