### PR TITLE
Fix: added subRates property to TaxRate datatype

### PR DESCRIPTION
**Pull request by daschy**

### CODE REVIEW

**Comment by daschy** [comment]
Hi,
I added the missing field subRates in the TaxRate. Could you please have a look? (@jenschude ) 
Thanks

**Comment by daschy** [comment]
Hi,

Is there any news about this PR?

Thanks

**Comment by jenschude** [comment]
Sorry for the late answer.

Will release it hopefully also today. Latest tomorrow.

**Comment by daschy** [comment]
Thanks!!

**Pull request merged**
