### PR TITLE
Support CartDiscount Operations

### PR DESCRIPTION
**Pull request by brajivbala**
Solves #26

### CODE REVIEW

**Comment by jhumber** [comment]
@brajivbala Thanks for implementing the Cart Discounts endpoint!  Before I can merge your changes, there are a couple of updates needed to keep things consistent with the rest of the SDK.  My apologies as I know we don't have these guidelines explicitly stated anywhere yet:

1. The namespaces and directory names in the SDK should match up exactly with the project name in the documentation. For your contributions, this means the namespace should be commercetools.CartDiscounts (plural) should be used rather than commercetools.CartDiscount (singular).  Also, the CartDiscount directory should be renamed to CartDiscounts.

2. Only the required properties for an API entity should be used as constructor parameters in the corresponding SDK class.  Parameters marked as optional in the documentation should not be required for creating a new instance of the class.  So for the commercetools.CartDiscounts.CartDiscountDraft class, description, target, isActive, validFrom and validUntil should not be used as constructor parameters as they are not required.  This also applies to the first constructor in the commercetools.CartDiscounts.CartDiscountValue class.

3. This is not required right now, but strongly recommended: The CartDiscountValue entity can be treated as a group of entities that share a common type property: Relative, Absolute, and Gift Line Item. In the SDK, I would typically use a base object and inheritance to implement these classes so I would end up with a CartDiscountValue class that has a Type property and then have the following classes inherit from that class: RelativeCartDiscountValue, AbsoluteCartDiscountValue, and GiftLineItemCartDiscountValue.  You can see how this pattern works if you look at the existing commercetools.Messages.Message class and the classes that inherit from it in the commercetools.Messages namespace (commercetools.Messages.CategoryCreatedMessage, for example).  There is also a commercetools.Message.MessageFactory class that has a single Create() method, used to instantiate the correct class based on the type property returned from the API.

**Comment by brajivbala** [comment]
@jhumber  any idea why the integration tests are failing ?

**Comment by jhumber** [comment]
@brajivbala I believe it's because you don't have the required permissions to access the needed environment variables.

**Comment by nkuehn** [comment]
@brajivbala yes, the integration tests require a commercetools project configured that they are operating on.   
To avoid having API access secrets in public repositories like this you are either using an own commercetools test project to run them or create Pull Request and wait for the respective appveyor and travis results   ( @jayS-de am I correct in the assumption that they automatically build PRs ?) 

If you see yourself contributing more in the future I'm happy to hand you a client ID and secret for the integration test project so you can run them locally  in a more comparable way by setting the environment variables to that.

**Comment by jayS-de** [comment]
PRs from forked repositories can't be build with the stored credentials, this only works for PRs coming from the repository itself. This is a security feature to prevent exposure of the credentials by a fraudulent PR.

**Comment by nkuehn** [comment]
right..    Do the new GitHub permissions enable something like a PR, but no merge to master in the main repository for select contributors?    It would be very helpful to have something like that to foster OSS contributions in all our OSS projects.

**Comment by brajivbala** [comment]
@nkuehn @jayS-de  I suspect I cannot push (a branch) to your repository either, which leaves me no option , but to only work with forks. I would like to suggest the following. I am not sure if  it suits you.

* Create 2 Teams (NETSDKAdmin/NETSDKCollaborators)
    * NETSDKAdmin => CommerceTools Employees (Admin privileges)
    * NETSDKCollaborators => OSS Collaborators (Write privileges)
* Protect your master branch in the repository, such that only users of the NETSDKAdmin can merge to the master branch.
* You can protect multiple branches if you want to.
* This setup will be easier for administration (You just need to add the collaborator to the NETSDKCollaborators Team)

**Comment by jayS-de** [comment]
It's a company decision to not have teams in the organization with external people. But I protected the master branch now and gave @jhumber push rights for master. Additionally I added you as a contributor. So you should be now able to create branches at the repository itself.

**Comment by brajivbala** [comment]
@jayS-de  Thank you !

**Comment by jayS-de** [comment]
@brajivbala the build script has issues when using slashes inside the branch name. I fixed it and opened a PR. So as soon as it's merged you could rebase or merge master to your branch and the build should be working.

**Pull request merged**
