### PR TITLE
Cleanup net standard migration

### PR DESCRIPTION
**Pull request by jenschude**
Hi @purquhart ,

I removed the binary files from the packages folder and fixed the commercetools.NET.Tests.csproj. But I didn't got it working to execute the tests in Visual Studio in the Test Explorer. Maybe you have an idea?

This one doesn't hurry.

### CODE REVIEW

**Comment by brajivbala** [comment]
@jenschude  you probably need to set the  following appsettings

    <add key="commercetools.ProjectKey" value="%CTP_PROJECT_KEY%"/>
    <add key="commercetools.ClientSecret" value="%CTP_CLIENT_SECRET%"/>
    <add key="commercetools.ClientID" value="%CTP_CLIENT_ID%"/>

locally to run the tests. I run the tests in VS2017 locally with success.

**Comment by jenschude** [comment]
In VS2017 nUnit was always reporting no tests found in the tests.dll. It could only find the tests when switching the target framework to netcoreapp2.0. But then the app.config wasn't loaded anymore 😆 

Maybe I'm missing something on my local machine.

**Comment by brajivbala** [comment]
Could be something local
My test logs are as below.
[4/20/2018 3:25:08 PM Informational] ========== Run test finished: 2 run (0:00:02.5562115) ==========
[4/20/2018 3:25:32 PM Informational] ------ Run test started ------
[4/20/2018 3:25:32 PM Informational] NUnit Adapter 3.10.0.21: Test execution started
[4/20/2018 3:25:32 PM Informational] Running selected tests in C:\Software\commercetools-dotnet-sdk\commercetools.NET.Tests\bin\Debug\net461\commercetools.NET.Tests.dll
[4/20/2018 3:25:33 PM Informational] NUnit3TestExecutor converted 93 of 93 NUnit test cases
[4/20/2018 3:25:37 PM Informational] NUnit Adapter 3.10.0.21: Test execution complete
[4/20/2018 3:25:37 PM Informational] ========== Run test finished: 4 run (0:00:04.7009527) ==========

**Comment by purquhart** [comment]
Hi @jenschude I downloaded this commit and was unable to reproduce the error. 

The process I tried, was to download the commit, change the commercetools.NET.Tests app.config settings to connect to one of our CT projects, and then I built the solution in VS 2017, after which the tests showed up in the Test Explorer and ran successfully.

**Pull request merged**
